### PR TITLE
Declare single-argument (non-converting) constructors "explicit"

### PR DESCRIPTION
**Pull request by MarcoFalke**
Rebased on #4.

Closes #6, which stripped the original author.

### CODE REVIEW

**Comment by laanwj** [comment]
Probably needs rebase now that #4 is merged to reduce the commit list?

**Comment by MarcoFalke** [comment]
Done

**Comment by fanquake** [comment]
utACK fe805ea

**Comment by promag** [comment]
utACK fe805ea.

**Pull request merged**
